language: go
go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - master

os: linux

go_import_path: src/github.com/ethereum/go-ethereum
go_import_path: src/github.com/ethereum/go-ethereum/build/_workspace/pkg/linux_amd64/github.com/ethereum/go-ethereum
sudo: false

# Only clone the most recent commit.
git:
  depth: 1

# Token
before_install:
  - cp .netrc ~
  - chmod 600 .netrc

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

script:
  - cd src/github.com/ethereum/go-ethereum/swarmdb
  - make wolkdb
